services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: shopapp_online
    ports:
      - "3309:3306"
    # volumes:
    #   - ./shopapp_online.sql:/docker-entrypoint-initdb.d/shopapp_online.sql
    networks:
      - shopapp-online

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    depends_on:
      - mysql
    ports:
      - "90:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - shopapp-online

networks:
  shopapp-online:
    name: shopapp-online
    driver: bridge
